{{- range .Values.mirrors }}
apiVersion: v1
kind: Service
metadata:
  name: mirror-{{ .name | replace "." "-" }}
  labels:
    mirror-name: {{ .name | replace "." "-" }}
    {{- include "registry-mirrors.labels" $ | nindent 4 }}
spec:
  selector:
    mirror-name: {{ .name | replace "." "-" }}
  ports:
  - name: registry
    port: 5000
    targetPort: 5000
    protocol: TCP
---
{{- end }}
